######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 21 11:14:03 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += arm.h visual.h
SOURCES += main.cpp arm.cpp visual.h
TARGET +=arm

