######################################################################
# Automatically generated by qmake (1.07a) Thu Oct 22 14:14:33 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += MyServer.h arm.h
SOURCES += arm.cpp
#SOURCES += 
